name: wled_dart
description: WLED HTTP API for Dart
version: 0.0.1
repository: https://github.com/dector/wled-dart

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
